### ISSUE TITLE
problems with simple booking system

### ISSUE THREAD

**Issue by 14RScoutBoatCentre** [JackFurby/Bootscout-theme#18]
Hi Jack, I am trying to use a booking system with the bootscout theme and seem to have some incompatibility issues I am using the free version from https://wpbookingcalendar.com/  
The system works perfectly from the admin account however the public booking page gets stuck with a booking form, the form is OK but the "calendar" pick element just shows "Calendar is loading"  (and you need this bit to chose the date).
I noticed a javascript error "Uncaught TypeError: jQuery(...).datepick is not a function" this makes me think there may be a naming conflict.  
hey ho, I am not an expert .... any thoughts or suggestions to diagnose?

thanks
Trevor
p.s. site is https://www.14thrichmondsbc.org.uk/wordpress/

**Comment by JackFurby** [comment]
Hi @14RScoutBoatCentre,

Thank you for raising this issue. I have found the cause which turned out to be a duplicate jQuery enqueue which created a conflict with that plugin. An update will be pushed out over the weekend to address this.

Thanks,
Jack

**Comment by 14RScoutBoatCentre** [comment]
Thanks, that seems to have solved my problem
All the best
Trevor
