### ISSUE TITLE
Dropdown menu not working

### ISSUE THREAD

**Issue by jonlloyd1234** [JackFurby/Bootscout-theme#2]
Hi
I have installed the theme on 2 websites, but I can only get the dropdown menu to work on 1 of the sites. The other just wont allow the dropdown to appear and does nothing when clicked. Any ideas? (fyi I have no clue about programming)

**Comment by JackFurby** [comment]
Hi @jonlloyd1234,

If dropdown menus are working one one site but not another, the issue sounds as if it is somewhere in the configuration of the menu. Do you have menus within menus?

I do know of a few issues with dropdowns and will be working on a fix soon. Once that is done it may solve your issue.

**Comment by JackFurby** [comment]
I have just released version 1.4.1 in which the navbar has been completely overhauled and should fix any issue you had with menus. I will close this issue but if you face it again then feel free to open it up again.
