### ISSUE TITLE
Change the hyperlink colour

### ISSUE THREAD

**Issue by KodiBarks** [JackFurby/Bootscout-theme#3]
Hi Jack, 
Love the theme. 

Is there any chance you could make hyperlinks the same colour as the top bar?  

I would submit a pull request but i can't work out how to do it 

Many Thanks 

Joe Fletcher 

**Area Youth Commisioner**
Cardiff and the Vale of Glamorgan

**Comment by JackFurby** [comment]
Hi Joe,

Glad to hear you like the theme! This should be fairly simple to do. I can't promise on when it will be completed as I am currently working on a separate feature, but will be sure you let you know when it is done.

Thanks,
Jack

**Comment by JackFurby** [comment]
The change has now been completed and can be used in the latest release (1.4.1)
