### ISSUE TITLE
Cant seem to get the Hero image to the top of the page?

### ISSUE THREAD

**Issue by rozzer1234** [JackFurby/Bootscout-theme#5]
Hi, 

I have your theme installed on my webpage but even though I have selected the no title template I still get a gap at the top.... any ideas?

https://thaxtedscouts.org.uk/

cheers 

Rory

**Comment by JackFurby** [comment]
Hi @rozzer1234,

By the looks of it the hero image has been added to the page content. There is already a feature to add images directly under the navbar which will fix your issue. To use this feature, within edit page, you need to set a featured image. I have included two screen shots with the first including the forward facing page and the second within the page editor.

![Screenshot_2020-08-01 Test page – Bootscout](https://user-images.githubusercontent.com/22617974/89099527-f1736880-d3e7-11ea-9f17-9a60e369bde0.png)

![Screenshot_2020-08-01 Edit Page ‹ Bootscout — WordPress](https://user-images.githubusercontent.com/22617974/89099528-f33d2c00-d3e7-11ea-905d-8f4ca0d85189.png)

Hope this helps.

Thanks,
Jack
