### ISSUE TITLE
Menu displayed incorrectly 

### ISSUE THREAD

**Issue by rozzer1234** [JackFurby/Bootscout-theme#7]
Hi Jack,

Need your help again for some reason the top menus has started displaying incorrectly on my site.... not sure why as I haven’t made any changes? Any way to reset to default?

https://thaxtedscouts.org.uk/

**Comment by JackFurby** [comment]
Hi @rozzer1234,

It looks like you are no longer using this theme for your website. If you did not make the change I would ask anyone else with access about the changes.

Regards,
Jack
